# Set base image for NODE runtime 
FROM node:22

# Set working directory in the container to /app
WORKDIR /app

# Install ffmpeg in the container
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg

# Copy package.json and package-lock.json into the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the app source inside the docker image
COPY . .

# Make port 3000 available outside this container
EXPOSE 3000

# Define the command to run your app using CMD 'npm start'
CMD ["npm", "start"]